# Generated by Django 5.2.7 on 2025-10-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la société')),
                ('siren', models.CharField(max_length=9, unique=True, verbose_name='Numéro SIREN')),
                ('code_naf', models.CharField(blank=True, max_length=5, verbose_name='Code NAF')),
                ('secteur', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ('activite_detaille', models.TextField(blank=True, verbose_name='Activité détaillée')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, default='France', max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('forme_juridique', models.CharField(blank=True, max_length=100)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('derniere_annee_disponible', models.IntegerField(blank=True, help_text='Ex: 2024', null=True)),
                ('capitaux_propres', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ca_n', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires N")),
                ('ca_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires N-1")),
                ('ca_n2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires N-2")),
                ('resultat_exploitation_n', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Résultat d'exploitation N")),
                ('resultat_exploitation_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Résultat d'exploitation N-1")),
                ('resultat_exploitation_n2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Résultat d'exploitation N-2")),
                ('resultat_net_n', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat net N')),
                ('resultat_net_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat net N-1')),
                ('resultat_net_n2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat net N-2')),
                ('ebitda_n', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='EBITDA N')),
                ('ebitda_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='EBITDA N-1')),
                ('ebitda_n2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='EBITDA N-2')),
                ('effectif', models.IntegerField(blank=True, null=True, verbose_name='Effectif précis')),
                ('effectif_approximatif', models.CharField(blank=True, max_length=50, verbose_name="Tranche d'effectif")),
                ('numero_standard', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone standard')),
                ('email_standard', models.EmailField(blank=True, max_length=254, verbose_name='Email standard')),
                ('site_web', models.URLField(blank=True)),
                ('lien_linkedin', models.URLField(blank=True, verbose_name='Lien page LinkedIn')),
                ('maison_mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiales', to='api.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mandat', models.CharField(max_length=255, verbose_name='Nom du mandat (ex: Projet Phoenix)')),
                ('type_mandat', models.CharField(choices=[('SELL', 'Sell-Side (Cession)'), ('BUY', 'Buy-Side (Acquisition)'), ('FUND', 'Levée de fonds'), ('AUTRE', 'Autre')], max_length=10)),
                ('statut', models.CharField(choices=[('PROSP', 'Prospection'), ('EN_COURS', 'En cours'), ('CLOSING', 'En closing'), ('TERMINE', 'Terminé'), ('ABANDONNE', 'Abandonné')], max_length=10)),
                ('phase', models.CharField(blank=True, choices=[('PREPA', 'Préparation (Teaser, IM)'), ('MARKET', 'Phase de marketing'), ('NEGO', 'Négociation (LOI)'), ('DUE_DIL', 'Due Diligence'), ('SIGN', 'Signature (SPA)')], max_length=10)),
                ('valorisation_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valorisation estimée (€)')),
                ('honoraires_estimes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Honoraires estimés (€)')),
                ('acheteurs_potentiels', models.ManyToManyField(blank=True, related_name='mandats_achat_potentiel', to='api.societe')),
                ('cedants_potentiels', models.ManyToManyField(blank=True, related_name='mandats_cession_potentiel', to='api.societe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats_client', to='api.societe', verbose_name='Société cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominatif', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MME', 'Mme.'), ('AUTRE', 'Autre')], max_length=5)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email professionnel')),
                ('telephone_fixe', models.CharField(blank=True, max_length=20)),
                ('telephone_portable', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('statut', models.CharField(choices=[('A_QUALIFIER', 'À qualifier'), ('INJOIGNABLE', 'Injoignable'), ('PAS_DE_PROJET', 'Pas de projet actuellement'), ('CONTACT_EXPERT', 'Contact expert'), ('A_RELANCER', 'À relancer'), ('NE_PLUS_CONTACTER', 'Ne plus contacter')], default='A_QUALIFIER', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_dernier_mailing', models.DateTimeField(blank=True, null=True)),
                ('date_dernier_appel', models.DateTimeField(blank=True, null=True)),
                ('date_dernier_mail', models.DateTimeField(blank=True, null=True)),
                ('groupes', models.ManyToManyField(blank=True, related_name='contacts', to='api.groupe')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.societe')),
            ],
        ),
    ]
