# Generated by Django 5.2.7 on 2025-10-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='code_naf',
            field=models.CharField(blank=True, max_length=255, verbose_name='Code NAF'),
        ),
    ]
