# Generated by Django 5.2.7 on 2025-10-24 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_societe_code_naf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('EMAIL', 'Email'), ('RDV', 'Rendez-vous'), ('AUTRE', 'Autre')], max_length=10)),
                ('date_interaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('notes', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.contact')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.societe')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_interaction'],
            },
        ),
    ]
